/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Catholomew (https://sketchfab.com/Catholomew)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/minion-kingscrest-melee-hots-72d5d092d3e446c1b663eb363cfe73dc
Title: Minion - Kingscrest - Melee - HotS
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from '../assets/3d/minion.glb'

const Minion = ({ currentAnimation, ...props }) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        scene
    );
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop());

        actions['Armature_Stand_full'].play();

        if(actions[currentAnimation]) {
            actions[currentAnimation].play();
        }
    }, [actions, currentAnimation])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Armature_38">
                                <group name="GLTF_created_0">
                                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials["Material.001"]}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <group name="Mesh_37" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

export default Minion;
